spring.datasource.url=jdbc:postgresql://localhost:5432/salon_saas
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
server.port=8081

jwt.secret=VEhJU19JU19NWV9TVVBFUl9TRUNSRVRfSldUX0tFWV8xMjM0NTY3OAAADk=
jwt.expiration=259200000

